Extension { #name : #InstructionClient }

{ #category : #'*Opal-Simd-Bytecode' }
InstructionClient >> addAcrossFloat32Vector [
	
]

{ #category : #'*Opal-Simd-Bytecode' }
InstructionClient >> addFloat32Vector [
	
]

{ #category : #'*Opal-Simd-Bytecode' }
InstructionClient >> addFloat64Vector [
	
]

{ #category : #'*Opal-Simd-Bytecode' }
InstructionClient >> mulFloat32Vector [
	
]

{ #category : #'*Opal-Simd-Bytecode' }
InstructionClient >> pushFloat32ArrayToRegister [
	
]

{ #category : #'*Opal-Simd-Bytecode' }
InstructionClient >> pushFloat32RegisterElement [
	
]

{ #category : #'*Opal-Simd-Bytecode' }
InstructionClient >> pushFloat64ArrayToRegister [
	
]

{ #category : #'*Opal-Simd-Bytecode' }
InstructionClient >> storeFloat32RegisterIntoArray [
	
]

{ #category : #'*Opal-Simd-Bytecode' }
InstructionClient >> storeFloat64RegisterIntoArray [
]
