Extension { #name : #IRVisitor }

{ #category : #'*Opal-Simd-Bytecode' }
IRVisitor >> visitAddFloat32Vector: anIRAddVector [
]

{ #category : #'*Opal-Simd-Bytecode' }
IRVisitor >> visitAddFloat64Vector: anIRAddVector [
]

{ #category : #'*Opal-Simd-Bytecode' }
IRVisitor >> visitPushFloat32ArrayToRegister: pushArrayToRegister [
]

{ #category : #'*Opal-Simd-Bytecode' }
IRVisitor >> visitPushFloat64ArrayToRegister: pushArrayToRegister [
]

{ #category : #'*Opal-Simd-Bytecode' }
IRVisitor >> visitStoreFloat32RegisterIntoArray: storeRegisterIntoArray [
]

{ #category : #'*Opal-Simd-Bytecode' }
IRVisitor >> visitStoreFloat64RegisterIntoArray: storeRegisterIntoArray [
]
